import test from "node:test";
import assert from "node:assert/strict";
import { Pet, SeededRandom, calmDesktop, SPECIES, surfacesFromDesktop, PetPhysics, validatePack, PetOSSimulation } from "../dist/src/index.js";

test("high fatigue makes sleep dominate once inertia expires",()=>{const pet=new Pet({id:"a",name:"Nap",species:"cat",nowMs:0},new SeededRandom(1));pet.state.drives.fatigue=.99;pet.state.drives.play=.02;pet.state.behaviorSinceMs=-20_000;const w=calmDesktop(10_000);assert.equal(pet.tick(w,100).behavior,"sleep");});

test("fast nearby cursor can trigger chase",()=>{const pet=new Pet({id:"b",name:"Rocket",species:"cat",nowMs:0},new SeededRandom(2));pet.state.drives.fatigue=.02;pet.state.drives.play=.98;pet.state.behaviorSinceMs=-20_000;const w=calmDesktop(10_000);w.cursor={position:{x:310,y:710},speed:1800,distanceToPet:20,buttons:0};assert.equal(pet.tick(w,100).behavior,"chase_cursor");});

test("behavior inertia prevents twitching",()=>{const pet=new Pet({id:"c",name:"Steady",species:"cat",nowMs:0},new SeededRandom(3));pet.state.behavior="groom";pet.state.behaviorSinceMs=9_000;const w=calmDesktop(10_000);w.secondsSinceNewWindow=0;assert.equal(pet.tick(w,100).behavior,"groom");});

test("positive interactions teach surface preference",()=>{const pet=new Pet({id:"d",name:"Memory",species:"cat",nowMs:0},new SeededRandom(4));const w=calmDesktop(1000);w.currentSurface={id:"window:vscode",kind:"window",rect:{x:0,y:500,width:900,height:600},walkY:500,app:"Code.exe"};for(let i=0;i<8;i++)pet.receivePetting(w,1);assert.ok(pet.memory.preferenceForSurface("window:vscode")>.4);});

test("Keeper suppresses seek-user behavior in fullscreen",()=>{const pet=new Pet({id:"e",name:"Polite",species:"dog",nowMs:0},new SeededRandom(5));pet.state.drives.social=1;pet.state.drives.fatigue=.02;pet.state.behaviorSinceMs=-20_000;const w=calmDesktop(10_000);w.userActivity="fullscreen";const seek=pet.tick(w,100).allScores.find(x=>x.behavior==="seek_user");assert.ok(seek);assert.ok(seek.score<.45);});

test("species profiles genuinely differ",()=>{assert.ok(SPECIES.dog.defaultPersonality.sociability>SPECIES.cat.defaultPersonality.sociability);assert.ok((SPECIES.cat.behaviorBias.perch??0)>(SPECIES.dog.behaviorBias.perch??0));assert.ok(SPECIES.rabbit.movement.jumpSpeed>SPECIES.dog.movement.jumpSpeed);});

test("desktop geometry becomes walkable taskbar and window surfaces",()=>{const monitors=[{id:"m",rect:{x:0,y:0,width:1920,height:1080},workArea:{x:0,y:0,width:1920,height:1040},primary:true,scaleFactor:1}];const windows=[{id:"code",title:"Code",app:"Code.exe",rect:{x:400,y:200,width:900,height:700},visible:true,foreground:true,minimized:false}];const s=surfacesFromDesktop(monitors,windows);assert.ok(s.some(x=>x.kind==="taskbar"&&x.walkY===1040));assert.ok(s.some(x=>x.id==="window:code"&&x.walkY===200));});

test("physics lands a falling pet on a surface",()=>{const pet=new Pet({id:"fall",name:"Fall",species:"cat",nowMs:0,x:500,y:1000},new SeededRandom(6));pet.state.body.grounded=false;pet.state.body.velocity.y=100;const w=calmDesktop(1000);new PetPhysics().update(pet.state,w,100);assert.equal(pet.state.body.grounded,true);assert.equal(pet.state.body.surfaceId,"taskbar:primary");});

test("pet save/restore preserves learned memory",()=>{const pet=new Pet({id:"save",name:"Save",species:"cat",nowMs:0},new SeededRandom(7));const w=calmDesktop(1);w.currentSurface={id:"window:test",kind:"window",rect:{x:0,y:400,width:500,height:500},walkY:400};for(let i=0;i<5;i++)pet.receivePetting(w,1);const restored=Pet.fromSave(pet.save(),new SeededRandom(8));assert.equal(restored.state.name,"Save");assert.ok(restored.memory.preferenceForSurface("window:test")>.2);});

test("pack validator rejects nonsense and accepts community packs",()=>{assert.equal(validatePack({foo:"bar"}),null);const p=validatePack({id:"fox",name:"Fox",species:"cat",appearance:{coat:"#1",accent:"#2",eye:"#3",scale:1}});assert.equal(p?.id,"fox");});

test("multi-pet simulation advances every creature",()=>{const sim=new PetOSSimulation();sim.addPet(new Pet({id:"one",name:"One",species:"cat",nowMs:0,x:300,y:740}));sim.addPet(new Pet({id:"two",name:"Two",species:"dog",nowMs:0,x:350,y:740}));const monitor={id:"m",rect:{x:0,y:0,width:1280,height:800},workArea:{x:0,y:0,width:1280,height:760},primary:true,scaleFactor:1};const out=sim.tick({nowMs:5000,dtMs:16,monitors:[monitor],windows:[],cursorPosition:{x:900,y:300},cursorSpeed:0,cursorButtons:0,userActivity:"active",foregroundApp:null,secondsSinceNewWindow:999,interactionMode:false});assert.equal(out.pets.length,2);assert.ok(out.decisions.one);assert.ok(out.decisions.two);});

test("pet rides a desktop window when its surface moves",()=>{const sim=new PetOSSimulation();const pet=new Pet({id:"rider",name:"Rider",species:"cat",nowMs:0,x:500,y:300},new SeededRandom(9));pet.state.body.surfaceId="window:code";pet.state.body.grounded=true;pet.state.behavior="sit";pet.state.behaviorSinceMs=0;sim.addPet(pet);const monitor={id:"m",rect:{x:0,y:0,width:1280,height:800},workArea:{x:0,y:0,width:1280,height:760},primary:true,scaleFactor:1};const base={nowMs:5000,dtMs:16,monitors:[monitor],cursorPosition:{x:900,y:300},cursorSpeed:0,cursorButtons:0,userActivity:"active",foregroundApp:"Code.exe",secondsSinceNewWindow:999,interactionMode:false};sim.tick({...base,windows:[{id:"code",title:"Code",app:"Code.exe",rect:{x:400,y:300,width:600,height:400},visible:true,foreground:true,minimized:false}]});const before={...pet.state.body.position};sim.tick({...base,nowMs:5016,windows:[{id:"code",title:"Code",app:"Code.exe",rect:{x:440,y:320,width:600,height:400},visible:true,foreground:true,minimized:false}]});assert.ok(pet.state.body.position.x>=before.x+39);assert.ok(pet.state.body.position.y>=before.y+19);});

test("hungry pet can choose an available food bowl",()=>{const pet=new Pet({id:"hungry",name:"Hungry",species:"dog",nowMs:0},new SeededRandom(10));pet.state.drives.hunger=1;pet.state.drives.fatigue=.02;pet.state.drives.play=.01;pet.state.drives.social=.01;pet.state.behaviorSinceMs=-20_000;const w=calmDesktop(10000);w.objects=[{id:"food",kind:"bowl",contents:"food",position:{x:340,y:1040},radius:18}];assert.equal(pet.tick(w,100).behavior,"eat");});
